[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"

[env]
  [env.production]
    RESEND_API_KEY = "placeholder"
